Enforce Gradle to use UTF-8
By default Gradle uses systems default encoding, if no specific
encoding is defined in the Gradle build script.
On most operation system (including Windows Server 2019 which is
used by Github Actions) this is UTF-8, but Windows 10 still uses
(like its predecessor) CP-1252 (also known as Windows-1252)
which does not fully compatible to UTF-8.

Until #247 (Publish condition for ReportEntryExtension) no
UTF-8 characters were used inside Pioneers code.
Since then the build breaks on most Windows systems,
because of unmappable UTF-8 characters,
which results in an error message like the following one:

`ReportEntryExtensionTests.java:377: error:
unmappable character for encoding Cp1252
"And the only word there spoken was the
whispered word, ÔÇ£Lenore?ÔÇ?"`

This PR fixes this build by forcing Gradle to explicitly
use UTF-8 for its build.

Issue: none
PR: #270